# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import simulator_pb2 as simulator__pb2


class AiddlSimulatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.doAction = channel.unary_unary(
                '/AiddlSimulator/doAction',
                request_serializer=simulator__pb2.Action.SerializeToString,
                response_deserializer=simulator__pb2.Result.FromString,
                )
        self.getState = channel.unary_unary(
                '/AiddlSimulator/getState',
                request_serializer=simulator__pb2.Empty.SerializeToString,
                response_deserializer=simulator__pb2.State.FromString,
                )
        self.setState = channel.unary_unary(
                '/AiddlSimulator/setState',
                request_serializer=simulator__pb2.State.SerializeToString,
                response_deserializer=simulator__pb2.Empty.FromString,
                )


class AiddlSimulatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def doAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiddlSimulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'doAction': grpc.unary_unary_rpc_method_handler(
                    servicer.doAction,
                    request_deserializer=simulator__pb2.Action.FromString,
                    response_serializer=simulator__pb2.Result.SerializeToString,
            ),
            'getState': grpc.unary_unary_rpc_method_handler(
                    servicer.getState,
                    request_deserializer=simulator__pb2.Empty.FromString,
                    response_serializer=simulator__pb2.State.SerializeToString,
            ),
            'setState': grpc.unary_unary_rpc_method_handler(
                    servicer.setState,
                    request_deserializer=simulator__pb2.State.FromString,
                    response_serializer=simulator__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AiddlSimulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AiddlSimulator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def doAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AiddlSimulator/doAction',
            simulator__pb2.Action.SerializeToString,
            simulator__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AiddlSimulator/getState',
            simulator__pb2.Empty.SerializeToString,
            simulator__pb2.State.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def setState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AiddlSimulator/setState',
            simulator__pb2.State.SerializeToString,
            simulator__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
