# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: planner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rplanner.proto\"\x1a\n\x07Problem\x12\x0f\n\x07problem\x18\x01 \x01(\t\"*\n\x08Solution\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x02 \x03(\t2+\n\x0c\x41iddlPlanner\x12\x1b\n\x04plan\x12\x08.Problem\x1a\t.Solutionb\x06proto3')



_PROBLEM = DESCRIPTOR.message_types_by_name['Problem']
_SOLUTION = DESCRIPTOR.message_types_by_name['Solution']
Problem = _reflection.GeneratedProtocolMessageType('Problem', (_message.Message,), {
  'DESCRIPTOR' : _PROBLEM,
  '__module__' : 'planner_pb2'
  # @@protoc_insertion_point(class_scope:Problem)
  })
_sym_db.RegisterMessage(Problem)

Solution = _reflection.GeneratedProtocolMessageType('Solution', (_message.Message,), {
  'DESCRIPTOR' : _SOLUTION,
  '__module__' : 'planner_pb2'
  # @@protoc_insertion_point(class_scope:Solution)
  })
_sym_db.RegisterMessage(Solution)

_AIDDLPLANNER = DESCRIPTOR.services_by_name['AiddlPlanner']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROBLEM._serialized_start=17
  _PROBLEM._serialized_end=43
  _SOLUTION._serialized_start=45
  _SOLUTION._serialized_end=87
  _AIDDLPLANNER._serialized_start=89
  _AIDDLPLANNER._serialized_end=132
# @@protoc_insertion_point(module_scope)
