# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orchestrator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='orchestrator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12orchestrator.proto\"\x07\n\x05\x45mpty\"\x16\n\x05State\x12\r\n\x05state\x18\x01 \x01(\t\"\x14\n\x04Goal\x12\x0c\n\x04goal\x18\x01 \x01(\t\"\x18\n\x06\x41\x63tion\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\t\"*\n\x08Solution\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x02 \x03(\t\"\x1a\n\x07Problem\x12\x0f\n\x07problem\x18\x01 \x01(\t2\xc9\x01\n\rAiddlExecutor\x12\"\n\x0f\x61ssembleProblem\x12\x05.Goal\x1a\x08.Problem\x12\x1f\n\x0c\x64oNextAction\x12\x06.Empty\x1a\x07.Action\x12+\n\x15processPlanningResult\x12\t.Solution\x1a\x07.Result\x12&\n\x13processActionResult\x12\x07.Result\x1a\x06.Empty\x12\x1e\n\x0cprocessState\x12\x06.State\x1a\x06.Empty2\x8b\x01\n\x07MazeGUI\x12\x1c\n\x0brequestTask\x12\x06.Empty\x1a\x05.Goal\x12$\n\x11processTaskResult\x12\x07.Result\x1a\x06.Empty\x12\x1a\n\x08getState\x12\x06.Empty\x1a\x06.State\x12 \n\x0evisualizeState\x12\x06.State\x1a\x06.Empty2+\n\x0c\x41iddlPlanner\x12\x1b\n\x04plan\x12\x08.Problem\x1a\t.Solution2f\n\x0e\x41iddlSimulator\x12\x1c\n\x08\x64oAction\x12\x07.Action\x1a\x07.Result\x12\x1a\n\x08getState\x12\x06.Empty\x1a\x06.State\x12\x1a\n\x08setState\x12\x06.State\x1a\x06.Emptyb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=29,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='State.state', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=53,
)


_GOAL = _descriptor.Descriptor(
  name='Goal',
  full_name='Goal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal', full_name='Goal.goal', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=75,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='Action.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=101,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='Result.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=127,
)


_SOLUTION = _descriptor.Descriptor(
  name='Solution',
  full_name='Solution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Solution.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='Solution.action', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=171,
)


_PROBLEM = _descriptor.Descriptor(
  name='Problem',
  full_name='Problem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='problem', full_name='Problem.problem', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=199,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['Goal'] = _GOAL
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Solution'] = _SOLUTION
DESCRIPTOR.message_types_by_name['Problem'] = _PROBLEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:State)
  })
_sym_db.RegisterMessage(State)

Goal = _reflection.GeneratedProtocolMessageType('Goal', (_message.Message,), {
  'DESCRIPTOR' : _GOAL,
  '__module__' : 'orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:Goal)
  })
_sym_db.RegisterMessage(Goal)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:Action)
  })
_sym_db.RegisterMessage(Action)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)

Solution = _reflection.GeneratedProtocolMessageType('Solution', (_message.Message,), {
  'DESCRIPTOR' : _SOLUTION,
  '__module__' : 'orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:Solution)
  })
_sym_db.RegisterMessage(Solution)

Problem = _reflection.GeneratedProtocolMessageType('Problem', (_message.Message,), {
  'DESCRIPTOR' : _PROBLEM,
  '__module__' : 'orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:Problem)
  })
_sym_db.RegisterMessage(Problem)



_AIDDLEXECUTOR = _descriptor.ServiceDescriptor(
  name='AiddlExecutor',
  full_name='AiddlExecutor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=202,
  serialized_end=403,
  methods=[
  _descriptor.MethodDescriptor(
    name='assembleProblem',
    full_name='AiddlExecutor.assembleProblem',
    index=0,
    containing_service=None,
    input_type=_GOAL,
    output_type=_PROBLEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='doNextAction',
    full_name='AiddlExecutor.doNextAction',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ACTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='processPlanningResult',
    full_name='AiddlExecutor.processPlanningResult',
    index=2,
    containing_service=None,
    input_type=_SOLUTION,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='processActionResult',
    full_name='AiddlExecutor.processActionResult',
    index=3,
    containing_service=None,
    input_type=_RESULT,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='processState',
    full_name='AiddlExecutor.processState',
    index=4,
    containing_service=None,
    input_type=_STATE,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AIDDLEXECUTOR)

DESCRIPTOR.services_by_name['AiddlExecutor'] = _AIDDLEXECUTOR


_MAZEGUI = _descriptor.ServiceDescriptor(
  name='MazeGUI',
  full_name='MazeGUI',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=406,
  serialized_end=545,
  methods=[
  _descriptor.MethodDescriptor(
    name='requestTask',
    full_name='MazeGUI.requestTask',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_GOAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='processTaskResult',
    full_name='MazeGUI.processTaskResult',
    index=1,
    containing_service=None,
    input_type=_RESULT,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getState',
    full_name='MazeGUI.getState',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='visualizeState',
    full_name='MazeGUI.visualizeState',
    index=3,
    containing_service=None,
    input_type=_STATE,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAZEGUI)

DESCRIPTOR.services_by_name['MazeGUI'] = _MAZEGUI


_AIDDLPLANNER = _descriptor.ServiceDescriptor(
  name='AiddlPlanner',
  full_name='AiddlPlanner',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=547,
  serialized_end=590,
  methods=[
  _descriptor.MethodDescriptor(
    name='plan',
    full_name='AiddlPlanner.plan',
    index=0,
    containing_service=None,
    input_type=_PROBLEM,
    output_type=_SOLUTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AIDDLPLANNER)

DESCRIPTOR.services_by_name['AiddlPlanner'] = _AIDDLPLANNER


_AIDDLSIMULATOR = _descriptor.ServiceDescriptor(
  name='AiddlSimulator',
  full_name='AiddlSimulator',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=592,
  serialized_end=694,
  methods=[
  _descriptor.MethodDescriptor(
    name='doAction',
    full_name='AiddlSimulator.doAction',
    index=0,
    containing_service=None,
    input_type=_ACTION,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getState',
    full_name='AiddlSimulator.getState',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setState',
    full_name='AiddlSimulator.setState',
    index=2,
    containing_service=None,
    input_type=_STATE,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AIDDLSIMULATOR)

DESCRIPTOR.services_by_name['AiddlSimulator'] = _AIDDLSIMULATOR

# @@protoc_insertion_point(module_scope)
