# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import unified_planning_pb2 as unified__planning__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x1a\x16unified_planning.proto\"\x07\n\x05\x45mpty\"\x1b\n\nAiddlState\x12\r\n\x05state\x18\x01 \x01(\t\"\x19\n\tAiddlGoal\x12\x0c\n\x04goal\x18\x01 \x01(\t\"\x1d\n\x0e\x41iddlOperators\x12\x0b\n\x03ops\x18\x01 \x03(\t\"\x1d\n\x0b\x41iddlAction\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\"\x1d\n\x0b\x41iddlResult\x12\x0e\n\x06result\x18\x01 \x01(\t2\x9b\x02\n\rAiddlExecutor\x12+\n\x0f\x61ssembleProblem\x12\n.AiddlGoal\x1a\x0c.PlanRequest\x12$\n\x0c\x64oNextAction\x12\x06.Empty\x1a\x0c.AiddlAction\x12<\n\x15processPlanningResult\x12\x15.PlanGenerationResult\x1a\x0c.AiddlResult\x12+\n\x13processActionResult\x12\x0c.AiddlResult\x1a\x06.Empty\x12#\n\x0cprocessState\x12\x0b.AiddlState\x1a\x06.Empty\x12\'\n\x0csetOperators\x12\x0f.AiddlOperators\x1a\x06.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=42
  _EMPTY._serialized_end=49
  _AIDDLSTATE._serialized_start=51
  _AIDDLSTATE._serialized_end=78
  _AIDDLGOAL._serialized_start=80
  _AIDDLGOAL._serialized_end=105
  _AIDDLOPERATORS._serialized_start=107
  _AIDDLOPERATORS._serialized_end=136
  _AIDDLACTION._serialized_start=138
  _AIDDLACTION._serialized_end=167
  _AIDDLRESULT._serialized_start=169
  _AIDDLRESULT._serialized_end=198
  _AIDDLEXECUTOR._serialized_start=201
  _AIDDLEXECUTOR._serialized_end=484
# @@protoc_insertion_point(module_scope)
